#!/bin/bash
# =========================================================================
# =========================================================================
#
#	office-setup
#	  office-setup docker run command for Libre Office 5.4.4-2 
#		in a Debian 9.3 (Stretch) docker image.
#
# =========================================================================
#
# @author Jay Wheeler.
# @version 0.0.1
# @copyright © 2017. EarthWalk Software.
# @license Licensed under the Academic Free License version 3.0
# @package debian-libreoffice
# @subpackage office-setup
#
# =========================================================================
#
#	Copyright © 2017. EarthWalk Software
#	Licensed under the Academic Free License, version 3.0.
#
#	Refer to the file named License.txt provided with the source,
#	or from
#
#		http://opensource.org/licenses/academic.php
#
# =========================================================================
# =========================================================================
#
#   A copy of the setup command. Since it only copies files to the supplied
#   /userbin, it may run as often as needed (e.g. - the libreoffice container
#   has been removed and re-created).
#
# =========================================================================

docker run --name=office -v ${HOME}/bin:/userbin libreoffice:5.4.4 libresetup
